//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMonitor_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public string Symbol { get; set; }
        public string Nimi { get; set; }
        public string Maa { get; set; }
    }
}
