//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMonitor_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int ID { get; set; }
        public string Kayttaja { get; set; }
        public string Yritys { get; set; }
        public Nullable<int> MaaraYht { get; set; }
        public Nullable<decimal> HankintaArvo { get; set; }
        public Nullable<decimal> aHintaNyt { get; set; }
        public Nullable<decimal> ArvoNytAll { get; set; }
        public Nullable<decimal> VoittoTappioE { get; set; }
        public Nullable<decimal> VoittoTappio_ { get; set; }
    }
}
