//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMonitor_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Transactions = new HashSet<Transactions>();
        }
        [Required(ErrorMessage = "Anna käyttäjätunnus")]
        public string KayttajaNimi { get; set; }
        public string Rooli { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Anna salasana")]
        public string Salasana { get; set; }
        public string Sahkoposti { get; set; }
        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
